name: Build APK for preview
on:
  pull_request:
    types:
      - ready_for_review

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with: 
          java-version: 17
          distribution: 'temurin'
          
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          build-tools-version: 33.0.0


      - name: Build APK
        run: ./gradlew assembleDebug
        env:
          JAVA_HOME: ${{ steps.setup-jdk.outputs.java-home }}

      - name: Upload APK (internal-testing)
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
